### ISSUE TITLE
FYI: Colour has already code for Adobe/Iridas Cube.

### ISSUE THREAD

**Issue by thomasmansencal** [yoonsikp/pycubelut#1]
Hi @yoonsikp,

Just an FYI but I noticed that you reimplemented some code we already have in Colour: https://github.com/colour-science/colour/blob/develop/colour/io/luts/iridas_cube.py

It might help to reduce the size of your `CubeLut` class.

Cheers,

Thomas

**Comment by yoonsikp** [comment]
Thank you for the info. I will take a look and see if I can implement my `CubeLUT` class as a child class of your LUT3D Class.
